language: go

go:
- "1.x"
- "1.11.x"

go_import_path: github.com/gieseladev/lyricsfindergo

deploy:
  provider: releases
  api_key: meak secure boi
  file: pass
  skip_cleanup: true
  on:
    tags: true